// flow-typed signature: d752a1730940de8f299707b22fb7e37d
// flow-typed version: <<STUB>>/wdio-phantomjs-service_v^0.2.2/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'wdio-phantomjs-service'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'wdio-phantomjs-service' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'wdio-phantomjs-service/launcher' {
  declare module.exports: any;
}

declare module 'wdio-phantomjs-service/lib/launcher' {
  declare module.exports: any;
}

// Filename aliases
declare module 'wdio-phantomjs-service/index' {
  declare module.exports: $Exports<'wdio-phantomjs-service'>;
}
declare module 'wdio-phantomjs-service/index.js' {
  declare module.exports: $Exports<'wdio-phantomjs-service'>;
}
declare module 'wdio-phantomjs-service/launcher.js' {
  declare module.exports: $Exports<'wdio-phantomjs-service/launcher'>;
}
declare module 'wdio-phantomjs-service/lib/launcher.js' {
  declare module.exports: $Exports<'wdio-phantomjs-service/lib/launcher'>;
}
